apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-bladerose
  namespace: gateway
spec:
  dnsNames:
    - "*.bladerose.me"
    - bladerose.me
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-bladerose
  usages:
    - digital signature
    - key encipherment
